export const GET_POPULAR_PRODUCTS_LOADING = "GET_POPULAR_PRODUCTS_LOADING";
export const GET_POPULAR_PRODUCTS_SUCCESS = "GET_POPULAR_PRODUCTS_SUCCESS";
export const GET_POPULAR_PRODUCTS_ERROR = "GET_POPULAR_PRODUCTS_ERROR";
