export const ADD_CART_ITEMS = "ADD_CART_ITEMS";
export const DECREMENT_CART_ITEM = "DECREMENT_CART_ITEM";
export const INCREMENT_CART_ITEM = "INCREMENT_CART_ITEM";
export const GET_CART_ITEMS = "GET_CART_ITEMS";
export const DELETE_CART_ITEMS = "DELETE_CART_ITEMS";
