export const GET_FEATURED_PRODUCTS_LOADING = "GET_FEATURED_PRODUCTS_LOADING";
export const GET_FEATURED_PRODUCTS_SUCCESS = "GET_FEATURED_PRODUCTS_SUCCESS";
export const GET_FEATURED_PRODUCTS_ERROR = "GET_FEATURED_PRODUCTS_ERROR";
